# Generated by Django 5.2.17 on 2026-08-05 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(choices=[('all', 'Все активные подписчики'), ('static', 'Фиксированный список'), ('filter', 'По условию')], default='all', max_length=16, verbose_name='Тип')),
                ('filter', models.JSONField(blank=True, default=dict, verbose_name='Условие')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Сегменты',
                'db_table': 'segment',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Таймзона')),
                ('locale', models.CharField(default='ru', max_length=16, verbose_name='Язык')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('source_version', models.DateTimeField(blank=True, null=True, verbose_name='Версия в Auth')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'db_table': 'subscriber',
                'indexes': [models.Index(fields=['is_active'], name='subscriber_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='SegmentMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='subscribers.segment')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='subscribers.subscriber')),
            ],
            options={
                'verbose_name': 'Участник сегмента',
                'verbose_name_plural': 'Участники сегмента',
                'db_table': 'segment_member',
                'constraints': [models.UniqueConstraint(fields=('segment', 'subscriber'), name='segment_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='ChannelOptout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (не реализован)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], max_length=32, verbose_name='Канал')),
                ('category', models.CharField(blank=True, choices=[('marketing', 'Маркетинг'), ('digest', 'Подборка'), ('system', 'Системное'), ('transactional', 'Транзакционное (отписка невозможна)')], default='', max_length=32, verbose_name='Категория')),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optouts', to='subscribers.subscriber', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Отписка',
                'verbose_name_plural': 'Отписки',
                'db_table': 'channel_optout',
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'channel', 'category'), name='channel_optout_unique')],
            },
        ),
    ]
