# Generated by Django 5.2.17 on 2026-08-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeloptout',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (мгновенно в кабинет)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], max_length=32, verbose_name='Канал'),
        ),
    ]
