"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

from example.config import settings as env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.DEBUG

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'movies',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'example.middleware.RequestIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env.SQL_ENGINE,
        'NAME': env.POSTGRES_DB,
        'USER': env.POSTGRES_USER,
        'PASSWORD': env.POSTGRES_PASSWORD,
        'HOST': env.SQL_HOST,
        'PORT': env.SQL_PORT,
        'OPTIONS': {
            'options': env.SQL_OPTIONS,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model + SSO through the Auth service.
AUTH_USER_MODEL = 'users.User'

# Порядок важен: сначала пробуем Auth-сервис, затем — локальный ModelBackend.
# Второй бэкенд обеспечивает изящную деградацию: если Auth-сервис недоступен,
# локальный суперпользователь Django всё ещё сможет войти в админку.
AUTHENTICATION_BACKENDS = [
    'users.auth_backend.AuthServiceBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Настройки интеграции с Auth-сервисом.
AUTH_API_URL = env.AUTH_API_URL
AUTH_API_TIMEOUT = env.AUTH_API_TIMEOUT
AUTH_API_MAX_ATTEMPTS = env.AUTH_API_MAX_ATTEMPTS


# --- Логирование ------------------------------------------------------------
# Раньше LOGGING в проекте не было ВООБЩЕ: действовал дефолт Django, который при
# DEBUG=False отправляет в консоль только django.server и записи уровня WARNING+
# и не знает ни про JSON, ни про поле service. Админка была единственным
# сервисом стенда, чьи строки в общем хранилище логов нельзя было ни
# отфильтровать по сервису, ни разобрать на поля.
#
# Форматтер — свой (example/logging_json.py): проект вне uv-workspace и
# practix_core импортировать не может. Набор и порядок ключей совпадают с
# библиотечными намеренно — это один индекс и один набор полей в Kibana.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {'()': 'example.logging_json.JsonFormatter', 'service': env.OTEL_SERVICE_NAME},
        'verbose': {'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            # 'ext://sys.stdout', а не sys.stdout: dictConfig разрешает такие
            # ссылки сам, и settings.py остаётся без импорта sys.
            'stream': 'ext://sys.stdout',
            'formatter': 'json' if env.LOG_JSON else 'verbose',
        },
    },
    'root': {'handlers': ['console'], 'level': env.LOG_LEVEL},
    'loggers': {
        # django.request — источник записей о 4xx/5xx: без явного логгера
        # исключение во вьюхе видно только по traceback'у uwsgi, то есть уже не
        # как структурная запись.
        'django': {'handlers': ['console'], 'level': env.LOG_LEVEL, 'propagate': False},
        # django.db.backends на DEBUG печатает КАЖДЫЙ SQL-запрос.
        'django.db.backends': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}
