# Generated by Django 5.2.17 on 2026-08-05 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (не реализован)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], default='email', max_length=32, verbose_name='Канал')),
                ('subject_template', models.CharField(blank=True, default='', max_length=512, verbose_name='Тема')),
                ('body_template', models.TextField(verbose_name='Тело')),
                ('body_format', models.CharField(choices=[('html', 'HTML'), ('text', 'Текст')], default='html', max_length=8, verbose_name='Формат')),
                ('allowed_variables', models.JSONField(blank=True, default=list, help_text='Список имён, доступных в шаблоне', verbose_name='Разрешённые переменные')),
                ('sample_context', models.JSONField(blank=True, default=dict, help_text='На нём шаблон проверяется при сохранении', verbose_name='Пример контекста')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='Ревизия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'db_table': 'message_template',
                'ordering': ['name'],
            },
        ),
    ]
