# Generated by Django 5.2.17 on 2026-08-05 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_event_bindings_and_targeted_runs'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (не реализован)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], max_length=32, verbose_name='Канал')),
                ('category', models.CharField(choices=[('marketing', 'Маркетинг'), ('digest', 'Подборка'), ('system', 'Системное'), ('transactional', 'Транзакционное (отписка невозможна)')], max_length=32, verbose_name='Категория')),
                ('subject', models.CharField(blank=True, default='', max_length=512, verbose_name='Тема')),
                ('preview', models.CharField(blank=True, default='', max_length=1024, verbose_name='Превью')),
                ('event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип события')),
                ('content_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Идентификатор контента')),
                ('sent_at', models.DateTimeField(verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='campaigns.campaign', verbose_name='Рассылка')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='subscribers.subscriber', verbose_name='Подписчик')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_message', to='campaigns.deliverytask', verbose_name='Задача доставки')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'db_table': 'inbox_message',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['subscriber', '-sent_at'], name='inbox_subscriber_sent_idx')],
            },
        ),
    ]
