# Generated by Django 5.2.17 on 2026-08-05 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (не реализован)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], default='email', max_length=32, verbose_name='Способ доставки')),
                ('content_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Ключ контента')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Общие переменные шаблона для всей рассылки', verbose_name='Контекст')),
                ('category', models.CharField(choices=[('marketing', 'Маркетинг'), ('digest', 'Подборка'), ('system', 'Системное'), ('transactional', 'Транзакционное (отписка невозможна)')], default='marketing', max_length=32, verbose_name='Категория')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('queued', 'Поставлена в очередь'), ('running', 'Отправляется'), ('done', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='draft', max_length=16, verbose_name='Статус')),
                ('respect_quiet_hours', models.BooleanField(default=True, verbose_name='Не писать ночью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('recipients_total', models.PositiveIntegerField(default=0, verbose_name='Получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('segment', models.ForeignKey(blank=True, help_text='Пусто — все активные подписчики', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='subscribers.segment', verbose_name='Сегмент')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='content.messagetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('immediate', 'Сразу'), ('deferred', 'Отложенная'), ('recurring', 'Повторяющаяся')], default='immediate', max_length=16, verbose_name='Тип')),
                ('run_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправить в')),
                ('cron_expression', models.CharField(blank=True, default='', help_text='Например, «0 12 * * 5» — каждую пятницу в полдень', max_length=128, verbose_name='Расписание (cron)')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Таймзона расписания')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('max_runs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум запусков')),
                ('catchup', models.BooleanField(default=False, verbose_name='Догонять пропущенные')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Следующий запуск')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('runs_count', models.PositiveIntegerField(default=0, verbose_name='Запусков')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'db_table': 'campaign_schedule',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (не реализован)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16)),
                ('skip_reason', models.CharField(blank=True, choices=[('opted_out', 'Отписан'), ('no_address', 'Нет адреса'), ('inactive', 'Неактивен'), ('stale_event', 'Событие протухло'), ('channel_unavailable', 'Канал не реализован')], default='', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='subscribers.subscriber')),
            ],
            options={
                'verbose_name': 'Задача доставки',
                'verbose_name_plural': 'Задачи доставки',
                'db_table': 'delivery_task',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('result', models.CharField(choices=[('sent', 'Отправлено'), ('retry', 'Повтор'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='campaigns.deliverytask')),
            ],
            options={
                'verbose_name': 'Попытка доставки',
                'verbose_name_plural': 'Попытки доставки',
                'db_table': 'delivery_attempt',
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=64)),
                ('last_seen_value', models.PositiveSmallIntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_notification_send', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_subscriptions', to='subscribers.subscriber')),
            ],
            options={
                'verbose_name': 'Подписка на контент',
                'verbose_name_plural': 'Подписки на контент',
                'db_table': 'notification_subscription',
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange', models.CharField(max_length=128)),
                ('routing_key', models.CharField(max_length=255)),
                ('body', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Исходящее сообщение',
                'verbose_name_plural': 'Исходящие сообщения',
                'db_table': 'outbox_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['created_at'], name='outbox_unpublished_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ запуска')),
                ('planned_for', models.DateTimeField(verbose_name='Плановое время')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('fanning_out', 'Разворачивается'), ('published', 'Опубликован'), ('failed', 'Ошибка')], default='planned', max_length=16, verbose_name='Статус')),
                ('subject_snapshot', models.CharField(blank=True, default='', max_length=512)),
                ('body_snapshot', models.TextField(blank=True, default='')),
                ('template_revision', models.PositiveIntegerField(default=1)),
                ('is_html', models.BooleanField(default=True)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='campaigns.campaign')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='campaigns.campaignschedule')),
            ],
            options={
                'verbose_name': 'Запуск рассылки',
                'verbose_name_plural': 'Запуски рассылок',
                'db_table': 'scheduled_run',
                'ordering': ['-planned_for'],
            },
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.scheduledrun'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaign_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationsubscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'content_id', 'kind'), name='notification_subscription_unique'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['campaign', 'status'], name='delivery_task_camp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['status', 'queued_at'], name='delivery_task_stat_queued_idx'),
        ),
    ]
