# Generated by Django 5.2.17 on 2026-08-05 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user.registered', 'Регистрация пользователя'), ('film.published', 'Появился новый фильм'), ('notification.direct', 'Прямое сообщение (свободный формат)')], max_length=64, unique=True, verbose_name='Событие')),
                ('audience', models.CharField(choices=[('subject', 'Только тот, о ком событие'), ('campaign', 'Аудитория рассылки')], default='subject', max_length=16, verbose_name='Аудитория')),
                ('upsert_subscriber', models.BooleanField(default=False, verbose_name='Заводить подписчика из события')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('description', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Привязка события',
                'verbose_name_plural': 'Привязки событий',
                'db_table': 'event_binding',
                'ordering': ['event_type'],
            },
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='audience_subscriber',
            field=models.ForeignKey(blank=True, help_text='Пусто — аудитория рассылки целиком', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_runs', to='subscribers.subscriber', verbose_name='Единственный получатель'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='channel_override',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('websocket', 'Websocket (не реализован)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], default='', max_length=32, verbose_name='Канал события'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='context_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='Переменные события'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='event_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID события'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Тип события'),
        ),
        migrations.AddIndex(
            model_name='scheduledrun',
            index=models.Index(fields=['event_type', '-created_at'], name='scheduled_run_event_idx'),
        ),
        migrations.AddField(
            model_name='eventbinding',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_bindings', to='campaigns.campaign', verbose_name='Рассылка'),
        ),
    ]
