# Generated by Django 5.2.17 on 2026-08-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_event_bindings_and_targeted_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (мгновенно в кабинет)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], default='email', max_length=32, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket (мгновенно в кабинет)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('opted_out', 'Отписан'), ('no_address', 'Нет адреса'), ('inactive', 'Неактивен'), ('stale_event', 'Событие протухло'), ('channel_unavailable', 'Канал не реализован'), ('unknown_user', 'Нет в Auth')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='scheduledrun',
            name='channel_override',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('websocket', 'Websocket (мгновенно в кабинет)'), ('push', 'Push (не реализован)'), ('sms', 'SMS (не реализован)')], default='', max_length=32, verbose_name='Канал события'),
        ),
    ]
